# Generated by Django 6.0.6 on 2026-07-22 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='media_titile',
            new_name='media_title',
        ),
    ]
