# Generated by Django 6.0.6 on 2026-06-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('release_year', models.IntegerField(max_length=4)),
                ('rating', models.CharField(max_length=5)),
                ('length', models.IntegerField(max_length=3)),
                ('genre', models.CharField(max_length=150)),
                ('director', models.CharField(max_length=75)),
                ('cast', models.CharField(max_length=200)),
                ('IMDB_rating', models.FloatField(max_length=3)),
                ('format', models.CharField(max_length=50)),
                ('collection', models.CharField(max_length=50)),
                ('studio', models.CharField(max_length=75)),
            ],
        ),
    ]
