# Generated by Django 6.0.6 on 2026-06-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_database',
            name='IMDB_rating',
        ),
        migrations.AlterField(
            model_name='movie_database',
            name='length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie_database',
            name='release_year',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='movie_database',
            name='imdb_rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
