# Generated by Django 6.0.6 on 2026-06-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_database_imdb_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_database',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie_database',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
