# Generated by Django 6.0.6 on 2026-06-30 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_database_length_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie_database',
            new_name='Movie',
        ),
    ]
