# Generated by Django 6.0.6 on 2026-07-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='movies/'),
        ),
    ]
