# Generated by Django 6.0.6 on 2026-07-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movie_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video_file',
        ),
        migrations.AddField(
            model_name='movie',
            name='media_path',
            field=models.CharField(blank=True, help_text='Example: Movies/Alien (1979)/Alien (1979).mp4', max_length=500, null=True),
        ),
    ]
