# Generated by Django 6.0.6 on 2026-07-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_remove_movie_media_path_movie_imdb_id_movie_overview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
