# Generated by Django 6.0.6 on 2026-07-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_alter_movie_imdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='media_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
